name: Test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3
      - run: python -m pip install --upgrade pip
      - run: pip install poetry
      - run: poetry install
      - run: python -m compileall .
      - run: poetry run lint
      - run: poetry run test
